format = """\
[î‚¶](bg:#131921FF fg:#1C3A5E)\
$os\
[î‚°](fg:#1C3A5E bg:#2B4F7A)\
$time\
[î‚°](fg:#2B4F7A bg:#9A86FD)\
$directory\
[î‚° ](fg:#9A86FD bg:#FCF392)\
$git_branch\
$git_status\
$git_metrics\
[î‚° ](fg:#FCF392 bg:#3B76F0)\
[î‚° ](fg:#3B76F0 bg:#1C3A5E)\
$nodejs\
$rust\
$golang\
$conda\
$python\
$php\
$ruby\
[î‚° ](fg:#1C3A5E)\
$hostname\
$fill\
$cmd_duration\
\n$character\
"""

# ã‚³ãƒãƒ³ãƒ‰ãƒ©ã‚¤ãƒ³ã«1è¡Œåˆ†ã®ã‚¹ãƒšãƒ¼ã‚¹ã‚’å…¥ã‚Œã‚‹
add_newline = true

[fill]
symbol = ' '

[os]
format = "[$symbol]($style)"
style = "fg:#8DFBD2 bg:#1C3A5E"
disabled = false

[os.symbols]
Macos = " ï…¹ " # nf-fa-apple
Ubuntu = " ïŒ› " # nf-linux-ubuntu
Debian = " ïŒ† " # nf-linux-debian

[directory]
style = "fg:#FFFFFF bg:#9A86FD"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "â€¦/"
read_only = ' ó°Œ¾ '
read_only_style = 'fg:#FFFFFF bg:#9A86FD'
format = '[ ï„•  $path ]($style)[$read_only]($read_only_style)'

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
format = '[$symbol$branch(:$remote_branch) ]($style)'
symbol = "îœ‰ ï˜ "
style = "fg:#1C3A5E bg:#FCF392"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1C3A5E bg:#FCF392"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[$symbol$branch ]($style)"
symbol = "ï˜ "

[cmd_duration]
format = "[î‚¶](fg:18)[ó°… $duration](fg:bright-white bg:18)[î‚´](fg:18)"

[line_break]
disabled = true

[hostname]
ssh_only = true
ssh_symbol = "ğŸŒ "
format = '[$hostname]($style)'
style = "fg:#2D1C63 bg:#9A86FD"
disabled = false

[nodejs]
symbol = "îœ˜"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#8DFBD2 bg:#1C3A5E)]($style)'

[rust]
symbol = "î¨"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#8DFBD2 bg:#1C3A5E)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#8DFBD2 bg:#1C3A5E)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#8DFBD2 bg:#1C3A5E)]($style)'

[ruby]
symbol = "î‘" # nf-dev-ruby
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#8DFBD2 bg:#1C3A5E)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#E0E6F0 bg:#2B4F7A"
format = '[ ó±‘ $time ]($style)'

[conda]
symbol = 'îœ¼ ' # nf-dev-python
style = 'fg:#8DFBD2 bg:#1C3A5E'
format = '[ $symbol$environment ]($style)'
ignore_base = false

[python]
symbol = 'îœ¼ ' # nf-dev-python
format = '[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
pyenv_version_name = false
style = 'fg:#8DFBD2 bg:#1C3A5E'

[character]
success_symbol = '[â¯](bold green) '
error_symbol = '[âœ—](#E84D44) '
